# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5

development:
 <<: *default
 host: localhost
 database: hooliganz_dev
 username: elmirill
 password: password

test:
 <<: *default
 database: hoolihanz_test
 username: elmirill
 password:

production:
 <<: *default
 host: ENV["database_host"]
 database: ENV["database_name"]
 username: ENV["database_user"]
 password: ENV["database_pass"]